package modelo;
// Generated 27/10/2017 12:40:45 by Hibernate Tools 4.3.1



/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private Integer idGenero;
     private String nombre;

    public Genero() {
    }

    public Genero(String nombre) {
       this.nombre = nombre;
    }
   
    public Integer getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(Integer idGenero) {
        this.idGenero = idGenero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


