package modelo;
// Generated 30/10/2017 22:08:51 by Hibernate Tools 4.3.1



/**
 * Genero generated by hbm2java
 */
public class Genero  implements java.io.Serializable {


     private GeneroId id;

    public Genero() {
    }

    public Genero(GeneroId id) {
       this.id = id;
    }
   
    public GeneroId getId() {
        return this.id;
    }
    
    public void setId(GeneroId id) {
        this.id = id;
    }




}


