package modelo;
// Generated 30/10/2017 22:08:51 by Hibernate Tools 4.3.1



/**
 * GeneroId generated by hbm2java
 */
public class GeneroId  implements java.io.Serializable {


     private int idGenero;
     private String nombre;

    public GeneroId() {
    }

    public GeneroId(int idGenero, String nombre) {
       this.idGenero = idGenero;
       this.nombre = nombre;
    }
   
    public int getIdGenero() {
        return this.idGenero;
    }
    
    public void setIdGenero(int idGenero) {
        this.idGenero = idGenero;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof GeneroId) ) return false;
		 GeneroId castOther = ( GeneroId ) other; 
         
		 return (this.getIdGenero()==castOther.getIdGenero())
 && ( (this.getNombre()==castOther.getNombre()) || ( this.getNombre()!=null && castOther.getNombre()!=null && this.getNombre().equals(castOther.getNombre()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdGenero();
         result = 37 * result + ( getNombre() == null ? 0 : this.getNombre().hashCode() );
         return result;
   }   


}


