package modelo;
// Generated 30/10/2017 22:08:51 by Hibernate Tools 4.3.1



/**
 * Pais generated by hbm2java
 */
public class Pais  implements java.io.Serializable {


     private Integer idPais;
     private String nombre;
     private String idioma;

    public Pais() {
    }

    public Pais(String nombre, String idioma) {
       this.nombre = nombre;
       this.idioma = idioma;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(String idioma) {
        this.idioma = idioma;
    }




}


