package modelo;
// Generated 27/10/2017 12:40:45 by Hibernate Tools 4.3.1



/**
 * PaisDeOrigen generated by hbm2java
 */
public class PaisDeOrigen  implements java.io.Serializable {


     private Integer idPais;
     private String idioma;
     private String nombre;

    public PaisDeOrigen() {
    }

    public PaisDeOrigen(String idioma, String nombre) {
       this.idioma = idioma;
       this.nombre = nombre;
    }
   
    public Integer getIdPais() {
        return this.idPais;
    }
    
    public void setIdPais(Integer idPais) {
        this.idPais = idPais;
    }
    public String getIdioma() {
        return this.idioma;
    }
    
    public void setIdioma(String idioma) {
        this.idioma = idioma;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }




}


