package modelo;
// Generated 27/10/2017 12:40:45 by Hibernate Tools 4.3.1



/**
 * Pelicula generated by hbm2java
 */
public class Pelicula  implements java.io.Serializable {


     private Integer idPelicula;
     private String anioEstreno;
     private Byte disponible;
     private String duracion;
     private String fechaIngreso;
     private String nombre;
     private String tituloOriginal;
     private Integer idcalificacion;
     private Integer idgenero;
     private Integer idpaisdeorigen;

    public Pelicula() {
    }

    public Pelicula(String anioEstreno, Byte disponible, String duracion, String fechaIngreso, String nombre, String tituloOriginal, Integer idcalificacion, Integer idgenero, Integer idpaisdeorigen) {
       this.anioEstreno = anioEstreno;
       this.disponible = disponible;
       this.duracion = duracion;
       this.fechaIngreso = fechaIngreso;
       this.nombre = nombre;
       this.tituloOriginal = tituloOriginal;
       this.idcalificacion = idcalificacion;
       this.idgenero = idgenero;
       this.idpaisdeorigen = idpaisdeorigen;
    }
   
    public Integer getIdPelicula() {
        return this.idPelicula;
    }
    
    public void setIdPelicula(Integer idPelicula) {
        this.idPelicula = idPelicula;
    }
    public String getAnioEstreno() {
        return this.anioEstreno;
    }
    
    public void setAnioEstreno(String anioEstreno) {
        this.anioEstreno = anioEstreno;
    }
    public Byte getDisponible() {
        return this.disponible;
    }
    
    public void setDisponible(Byte disponible) {
        this.disponible = disponible;
    }
    public String getDuracion() {
        return this.duracion;
    }
    
    public void setDuracion(String duracion) {
        this.duracion = duracion;
    }
    public String getFechaIngreso() {
        return this.fechaIngreso;
    }
    
    public void setFechaIngreso(String fechaIngreso) {
        this.fechaIngreso = fechaIngreso;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getTituloOriginal() {
        return this.tituloOriginal;
    }
    
    public void setTituloOriginal(String tituloOriginal) {
        this.tituloOriginal = tituloOriginal;
    }
    public Integer getIdcalificacion() {
        return this.idcalificacion;
    }
    
    public void setIdcalificacion(Integer idcalificacion) {
        this.idcalificacion = idcalificacion;
    }
    public Integer getIdgenero() {
        return this.idgenero;
    }
    
    public void setIdgenero(Integer idgenero) {
        this.idgenero = idgenero;
    }
    public Integer getIdpaisdeorigen() {
        return this.idpaisdeorigen;
    }
    
    public void setIdpaisdeorigen(Integer idpaisdeorigen) {
        this.idpaisdeorigen = idpaisdeorigen;
    }




}


