package modelo;
// Generated 03/11/2017 21:33:50 by Hibernate Tools 4.3.1



/**
 * Alumnos generated by hbm2java
 */
public class Alumnos  implements java.io.Serializable {


     private Integer idAlumnos;
     private String nombre;
     private String apellido;
     private String telefono;

    public Alumnos() {
    }

	
    public Alumnos(String nombre, String apellido) {
        this.nombre = nombre;
        this.apellido = apellido;
    }
    public Alumnos(String nombre, String apellido, String telefono) {
       this.nombre = nombre;
       this.apellido = apellido;
       this.telefono = telefono;
    }
   
    public Integer getIdAlumnos() {
        return this.idAlumnos;
    }
    
    public void setIdAlumnos(Integer idAlumnos) {
        this.idAlumnos = idAlumnos;
    }
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }
    public String getApellido() {
        return this.apellido;
    }
    
    public void setApellido(String apellido) {
        this.apellido = apellido;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }




}


